services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_USER=user
      - DB_PASS=secret
      - DB_NAME=sernapesca

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sernapesca
      - MYSQL_USER=user
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: