"""Estructura corregida con tamaños

Revision ID: 2c06113c2081
Revises: 
Create Date: 2025-04-12 05:02:11.298842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c06113c2081'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_centro', sa.Integer(), nullable=False),
    sa.Column('titular', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('acs', sa.String(length=10), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_centro')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('responsable_centro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_inspeccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('inspeccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('centro_id', sa.Integer(), nullable=False),
    sa.Column('responsable_id', sa.Integer(), nullable=False),
    sa.Column('tipo_id', sa.Integer(), nullable=False),
    sa.Column('fiscalizador_1_id', sa.Integer(), nullable=True),
    sa.Column('fiscalizador_2_id', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['centro_id'], ['centro.id'], ),
    sa.ForeignKeyConstraint(['fiscalizador_1_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['fiscalizador_2_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['responsable_id'], ['responsable_centro.id'], ),
    sa.ForeignKeyConstraint(['tipo_id'], ['tipo_inspeccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inspeccion')
    op.drop_table('tipo_inspeccion')
    op.drop_table('responsable_centro')
    op.drop_table('funcionarios')
    op.drop_table('centro')
    # ### end Alembic commands ###
